# Generated by Django 5.0.6 on 2024-07-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateName', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('cat1', models.CharField(blank=True, max_length=100, null=True)),
                ('cat2', models.CharField(blank=True, max_length=100, null=True)),
                ('examstart', models.CharField(blank=True, max_length=100, null=True)),
                ('examend', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
