# Generated by Django 5.0.6 on 2024-07-15 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_images', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('news_description', models.TextField(blank=True, max_length=200, null=True)),
                ('admin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='home',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='home',
            name='news_images',
        ),
        migrations.RemoveField(
            model_name='home',
            name='news_topic',
        ),
        migrations.RemoveField(
            model_name='home',
            name='posted_date',
        ),
    ]
