# Generated by Django 5.0.6 on 2024-07-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news_remove_home_admin_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='admin_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='news_description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='news_images',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='slide',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
