# Generated by Django 5.0.6 on 2024-07-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slide_admin_name_slide_news_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='admin_name',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='news_description',
        ),
        migrations.AddField(
            model_name='slide',
            name='name',
            field=models.CharField(default='News', max_length=200),
        ),
    ]
