# Generated by Django 5.0.6 on 2024-07-16 11:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_slide_news_admin_slide_news_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_images', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('news_topic', models.CharField(blank=True, max_length=200, null=True)),
                ('news_description', models.TextField(blank=True, max_length=200, null=True)),
                ('news_admin', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_date', models.TimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scrol',
            fields=[
                ('scrol_images', models.ImageField(blank=True, default='default.jpeg', null=True, upload_to='')),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slide',
            name='name',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='news_admin',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='news_description',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='news_images',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='news_topic',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='posted_date',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='scrol_images',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='topic',
        ),
    ]
