# Generated by Django 5.0.6 on 2024-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_scrol_topic_alter_slide_slide_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrol',
            name='topic',
            field=models.CharField(default='Latest News', max_length=200),
        ),
        migrations.AlterField(
            model_name='slide',
            name='slide_topic',
            field=models.CharField(default='Latest News', max_length=200),
        ),
    ]
